export const IPC = {
  PTY_CREATE: 'pty:create',
  PTY_WRITE: 'pty:write',
  PTY_RESIZE: 'pty:resize',
  PTY_CLOSE: 'pty:close',
  PTY_GET_PROCESS_NAME: 'pty:getProcessName',
  PTY_DATA: 'pty:data',
  PTY_EXIT: 'pty:exit',
  GET_SESSION_INFO: 'session:getInfo',
  STATE_SAVE: 'state:save',
  STATE_LOAD: 'state:load',
  STATE_REQUEST_SAVE: 'state:requestSave',
  HOOK_STATUS: 'hook:status',
  HOOK_SESSION: 'hook:session',
  HOOK_PLAN: 'hook:plan',
  SPAWN_REQUEST: 'spawn:request',
  DISCOVER_TERMINALS: 'terminals:discover',
  PLAN_GET_FILES: 'plan:getFiles',
  PLAN_READ_FILE: 'plan:readFile',
  PICK_FOLDER: 'dialog:pickFolder',
  CHANGELOG_READ: 'changelog:read',
  WORKTREE_CREATE: 'worktree:create',
  UPDATE_CHECK: 'updates:check',
  UPDATE_INSTALL: 'updates:install',
} as const;
